# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aiden/projects/im-mpd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aiden/projects/im-mpd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aiden/projects/im-mpd/CMakeFiles /home/aiden/projects/im-mpd//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aiden/projects/im-mpd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named im-mpd

# Build rule for target.
im-mpd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 im-mpd
.PHONY : im-mpd

# fast build rule for target.
im-mpd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/build
.PHONY : im-mpd/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

imgui/backends/imgui_impl_glfw.o: imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui/backends/imgui_impl_glfw.o

# target to build an object file
imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui/backends/imgui_impl_glfw.cpp.o

imgui/backends/imgui_impl_glfw.i: imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.cpp.i

imgui/backends/imgui_impl_glfw.s: imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.cpp.s

imgui/backends/imgui_impl_opengl3.o: imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.o

# target to build an object file
imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.o

imgui/backends/imgui_impl_opengl3.i: imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.i

imgui/backends/imgui_impl_opengl3.s: imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

src/MpdClientWrapper.o: src/MpdClientWrapper.cpp.o
.PHONY : src/MpdClientWrapper.o

# target to build an object file
src/MpdClientWrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/MpdClientWrapper.cpp.o
.PHONY : src/MpdClientWrapper.cpp.o

src/MpdClientWrapper.i: src/MpdClientWrapper.cpp.i
.PHONY : src/MpdClientWrapper.i

# target to preprocess a source file
src/MpdClientWrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/MpdClientWrapper.cpp.i
.PHONY : src/MpdClientWrapper.cpp.i

src/MpdClientWrapper.s: src/MpdClientWrapper.cpp.s
.PHONY : src/MpdClientWrapper.s

# target to generate assembly for a file
src/MpdClientWrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/MpdClientWrapper.cpp.s
.PHONY : src/MpdClientWrapper.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/panels/MediaLibraryTree.o: src/panels/MediaLibraryTree.cpp.o
.PHONY : src/panels/MediaLibraryTree.o

# target to build an object file
src/panels/MediaLibraryTree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/MediaLibraryTree.cpp.o
.PHONY : src/panels/MediaLibraryTree.cpp.o

src/panels/MediaLibraryTree.i: src/panels/MediaLibraryTree.cpp.i
.PHONY : src/panels/MediaLibraryTree.i

# target to preprocess a source file
src/panels/MediaLibraryTree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/MediaLibraryTree.cpp.i
.PHONY : src/panels/MediaLibraryTree.cpp.i

src/panels/MediaLibraryTree.s: src/panels/MediaLibraryTree.cpp.s
.PHONY : src/panels/MediaLibraryTree.s

# target to generate assembly for a file
src/panels/MediaLibraryTree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/MediaLibraryTree.cpp.s
.PHONY : src/panels/MediaLibraryTree.cpp.s

src/panels/PanelBase.o: src/panels/PanelBase.cpp.o
.PHONY : src/panels/PanelBase.o

# target to build an object file
src/panels/PanelBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/PanelBase.cpp.o
.PHONY : src/panels/PanelBase.cpp.o

src/panels/PanelBase.i: src/panels/PanelBase.cpp.i
.PHONY : src/panels/PanelBase.i

# target to preprocess a source file
src/panels/PanelBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/PanelBase.cpp.i
.PHONY : src/panels/PanelBase.cpp.i

src/panels/PanelBase.s: src/panels/PanelBase.cpp.s
.PHONY : src/panels/PanelBase.s

# target to generate assembly for a file
src/panels/PanelBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/PanelBase.cpp.s
.PHONY : src/panels/PanelBase.cpp.s

src/panels/PlaybackButtons.o: src/panels/PlaybackButtons.cpp.o
.PHONY : src/panels/PlaybackButtons.o

# target to build an object file
src/panels/PlaybackButtons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/PlaybackButtons.cpp.o
.PHONY : src/panels/PlaybackButtons.cpp.o

src/panels/PlaybackButtons.i: src/panels/PlaybackButtons.cpp.i
.PHONY : src/panels/PlaybackButtons.i

# target to preprocess a source file
src/panels/PlaybackButtons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/PlaybackButtons.cpp.i
.PHONY : src/panels/PlaybackButtons.cpp.i

src/panels/PlaybackButtons.s: src/panels/PlaybackButtons.cpp.s
.PHONY : src/panels/PlaybackButtons.s

# target to generate assembly for a file
src/panels/PlaybackButtons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/PlaybackButtons.cpp.s
.PHONY : src/panels/PlaybackButtons.cpp.s

src/panels/SeekBar.o: src/panels/SeekBar.cpp.o
.PHONY : src/panels/SeekBar.o

# target to build an object file
src/panels/SeekBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/SeekBar.cpp.o
.PHONY : src/panels/SeekBar.cpp.o

src/panels/SeekBar.i: src/panels/SeekBar.cpp.i
.PHONY : src/panels/SeekBar.i

# target to preprocess a source file
src/panels/SeekBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/SeekBar.cpp.i
.PHONY : src/panels/SeekBar.cpp.i

src/panels/SeekBar.s: src/panels/SeekBar.cpp.s
.PHONY : src/panels/SeekBar.s

# target to generate assembly for a file
src/panels/SeekBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/SeekBar.cpp.s
.PHONY : src/panels/SeekBar.cpp.s

src/panels/VolumeControl.o: src/panels/VolumeControl.cpp.o
.PHONY : src/panels/VolumeControl.o

# target to build an object file
src/panels/VolumeControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/VolumeControl.cpp.o
.PHONY : src/panels/VolumeControl.cpp.o

src/panels/VolumeControl.i: src/panels/VolumeControl.cpp.i
.PHONY : src/panels/VolumeControl.i

# target to preprocess a source file
src/panels/VolumeControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/VolumeControl.cpp.i
.PHONY : src/panels/VolumeControl.cpp.i

src/panels/VolumeControl.s: src/panels/VolumeControl.cpp.s
.PHONY : src/panels/VolumeControl.s

# target to generate assembly for a file
src/panels/VolumeControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/im-mpd.dir/build.make CMakeFiles/im-mpd.dir/src/panels/VolumeControl.cpp.s
.PHONY : src/panels/VolumeControl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... im-mpd"
	@echo "... imgui"
	@echo "... imgui/backends/imgui_impl_glfw.o"
	@echo "... imgui/backends/imgui_impl_glfw.i"
	@echo "... imgui/backends/imgui_impl_glfw.s"
	@echo "... imgui/backends/imgui_impl_opengl3.o"
	@echo "... imgui/backends/imgui_impl_opengl3.i"
	@echo "... imgui/backends/imgui_impl_opengl3.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... src/MpdClientWrapper.o"
	@echo "... src/MpdClientWrapper.i"
	@echo "... src/MpdClientWrapper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/panels/MediaLibraryTree.o"
	@echo "... src/panels/MediaLibraryTree.i"
	@echo "... src/panels/MediaLibraryTree.s"
	@echo "... src/panels/PanelBase.o"
	@echo "... src/panels/PanelBase.i"
	@echo "... src/panels/PanelBase.s"
	@echo "... src/panels/PlaybackButtons.o"
	@echo "... src/panels/PlaybackButtons.i"
	@echo "... src/panels/PlaybackButtons.s"
	@echo "... src/panels/SeekBar.o"
	@echo "... src/panels/SeekBar.i"
	@echo "... src/panels/SeekBar.s"
	@echo "... src/panels/VolumeControl.o"
	@echo "... src/panels/VolumeControl.i"
	@echo "... src/panels/VolumeControl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

